### ISSUE TITLE
When running update.sh it overwrites my dovecot's extra.conf 

### ISSUE THREAD

**Issue by MrHappy** [Programmierus/ldap-mailcow#11]
It seems that everytime I run update.sh the customized extra.conf gets overwritten with this one.
Is there a way to prevent that from happening?

**Comment by Programmierus** [comment]
Just mount the version with your customization over [this file](https://github.com/Programmierus/ldap-mailcow/blob/master/templates/dovecot/extra.conf) and it should do it.

**Comment by MrHappy** [comment]
I added 
`        - ./data/conf/dovecot/extra.mine.conf:/conf/dovecot/extra.conf:rw`
under 
`      volumes:`

But it doesn't work because extra.mine.conf is not a directory.
I how would I go about it to get it mounted like you said?

**Comment by Programmierus** [comment]
Try:

```
- ./data/conf/dovecot/extra.mine.conf:/templates/dovecot/extra.conf:rw
```

**Comment by MrHappy** [comment]
Finally had the time to check it out... Works!
Thanks!
