### ISSUE TITLE
OpenLDAP Integration

### ISSUE THREAD

**Issue by QF0xB** [Programmierus/ldap-mailcow#2]
Hey,

Would an OpenLDAP integration be possible?
With more changes available for different setups?

Regards

**Comment by Programmierus** [comment]
Well, it's not what I need in my environment, and I don't expect to have that much free spare time to do it in the nearest future... The only thing I miss now is LDAP Filter parameter that I plan to implement soon. Of course, you are free to submit a PR.

**Comment by QF0xB** [comment]
API api/v1/add/mailbox: danger - access_denied

I am trying to migrate it, did this error occur before?

`API api/v1/add/mailbox: danger - access_denied`

Happens in the api.add_user function

**Comment by Programmierus** [comment]
No. Are u sure your IP is allowed as read-write in the mailcow API settings?

**Comment by QF0xB** [comment]
Yes
I am searching it, thanks for your help

**Comment by QF0xB** [comment]
Really strange behavior, I deactivated the api IPs check for a second and still the same error

**Comment by Programmierus** [comment]
Is the domain added for mailboxes you are trying to add?

**Comment by QF0xB** [comment]
Damn, I am so dumb xD It was a new mailcow setup f***

**Comment by Programmierus** [comment]
Glad I could help... I'll add this info to readme...

**Comment by QF0xB** [comment]
Hey could you maybe look at my repository?

It should work like yours, but with some small tweaks and changes.

Regards

[Klick](https://github.com/Stormfox2/ldap-mailcow)

**Comment by Programmierus** [comment]
It seems for me that you are using the code outside of docker extension (otherwise I don't know why you moved from environmental variables to a configuration file). These changes won't fit in the usage model with `docker-compose-override.xml`. 

Besides, that looks nice, but I don't see much of a sense. I'll add a filtering option later, and IMHO it'll do.

**Comment by QF0xB** [comment]
ldap(qbraendli@ketarion.eu,XXXXXX,<co0xpLWm/scxDEf6>): Password mismatch (for LDAP bind) (given password: XXXX )

Did you ever had this? In dovecot? The password is right, really dont know whats the problem

**Comment by Programmierus** [comment]
Nope

**Comment by LukasK13** [comment]
@Programmierus Thank you for your code!
@Stormfox2 I adapted the code and the templates for openldap: https://github.com/LukasK13/ldap-mailcow

**Comment by etique57** [comment]
Hello @LukasK13,

I would like to use your adapted code from Programmierus, do you have a Docker image?

Thanks a lot to both of you!

**Comment by LukasK13** [comment]
Unfortunately not. However, you can find the necessary Dockerfile to build the docker image in my linked repo above.
If you want to, I can upload the corresponding docker-compose file in the next days.

**Comment by Programmierus** [comment]
Quick info from my: I am on the go for the next week or so. I'll research this issue and if it would be confirmed, that API filed changed, I'll amend the initial image ASAP.

**Comment by etique57** [comment]
Thanks @LukasK13 I'd really appreciate.

In the mean time I'll dig into how to build a docker image from a dockerfile.

Thanks!

**Comment by LukasK13** [comment]
Done

**Comment by etique57** [comment]
I got it to work. Thanks a lot!

**Comment by theoneandonly-vector** [comment]
> Done

hey @LukasK13 As I try to use this project I found your fork and using it I am getting much further than here (users getting created)
```
Added filedb user: info@domain.tld (Active: True)
...
...
```

but I still got other issues. so maybe you can enable the "issues"-tab on your fork?:
https://github.com/LukasK13/ldap-mailcow

**Comment by LukasK13** [comment]
Hey @theoneandonly-vector 
I just enabled issues. As I‘m currently moving, I may not have the time to fix the issues, so a PR is more than welcome.
