### ISSUE TITLE
Client has quit the connection

### ISSUE THREAD

**Issue by MrHappy** [Programmierus/ldap-mailcow#24]
Today I had to reinstall my entire mailcow-config. I got everyting up and running again (for one user, me). Now I wanted to add your module again and followed the instructions to the letter. Unfortunately the mailusers are not populated.
Below you'll find the logging of ldap-mailcow & dovecot-mailcow.
What is the matter?

### docker-compose logs ldap-mailcow
New database file created: db/ldap-mailcow.sqlite3
Saved generated config file to conf/dovecot/ldap/passdb.conf
Saved generated config file to conf/dovecot/extra.conf
Config file conf/sogo/plist_ldap unchanged
One or more config files have been changed, please make sure to restart dovecot-mailcow and sogo-mailcow!
Sync finished, sleeping 300 seconds before next cycle

### docker-compose logs dovecot-mailcow
syslog-ng[119]: syslog-ng starting up; version='3.19.1'
dovecot: master: Dovecot v2.3.14.1 (9f0cfb6426) starting up for imap, sieve, lmtp, pop3
INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot: imap-login: Login: user=<<user>@<domain.org>>, method=PLAIN, rip=172.22.1.248, lip=172.22.1.250, mpid=137
dovecot: imap(<user>@<domain.org>)<137><LpEPVh3Imr6sFgH4>: Logged out in=225 out=1740 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
dovecot: imap-login: Login: user=<<user>@<domain.org>>, method=PLAIN, rip=172.22.1.248, lip=172.22.1.250, mpid=142
dovecot: imap-login: Login: user=<<user>@<domain.org>>, method=PLAIN, rip=172.22.1.248, lip=172.22.1.250, mpid=143
dovecot: imap(<user>@<domain.org>)<142><v3oeVh3Ior6sFgH4>: Logged out in=300 out=2500 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
dovecot: imap(<user>@<domain.org>)<143><Th8fVh3IrL6sFgH4>: Logged out in=342 out=3522 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=2 body_count=0 body_bytes=0

### and after that almost every minute in logging dovecot-mailcow
dovecot: lmtp(175): Connect from 172.22.1.2
dovecot: lmtp(175): Disconnect from 172.22.1.2: Client has quit the connection (state=READY)
dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.2, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.2, lip=172.22.1.250
dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.2, lip=172.22.1.250

Thanks in advance for any assistance.

**Comment by Programmierus** [comment]
For me it seems that LDAP request doesn't return any users. Bad LDAP FILTER setting?

**Comment by MrHappy** [comment]
Tried the same filtering through ldapsearch and it returns valid data.
Also this is an exact copy of my prior installation and there it worked (at least when I installed it, after installation there were no extra user accounts created, so I don't know for sure something else did not bork it).

**Comment by MrHappy** [comment]
@Programmierus can you give my any tips?

**Comment by Programmierus** [comment]
Needs remote investigation. Sorry I don't have any spare time atm for free support.

**Comment by MrHappy** [comment]
Deleted entire filter and now it works...

**Comment by changchichung** [comment]
> Deleted entire filter and now it works...

hello @MrHappy  ,  I have the same issue when I try to run mailcow and ldap-mailcow
I'm wondering did you make it works or not ?
and when you said " Deleted entire filter" , is that mean you delete the LDAP FILTER  line in docker-compose.yml file ?
