### ISSUE TITLE
LDAP login for Admins only

### ISSUE THREAD

**Issue by lucianlazar1983** [Programmierus/ldap-mailcow#4]
Hi there,
Any chance this could easily be modified in order to use LDAP authentication only for admins? What i mean is to allow domain admins and mailbox users login just fine using exosting MySQL but enable LDAP only for server admins. Thanks!

**Comment by Programmierus** [comment]
The tool itself does not restrict mysql (or any other) authentication methods allowing them to work simultaneously. All you have to do is to adjust the filter on line 42 [here](https://github.com/Programmierus/ldap-mailcow/blob/master/syncer.py), restricting the sync to the group you need (admins in your case). 

It's planned to allow LDAP Filter configuration through environmental variable, but I still can't find an hour to finish it.

**Comment by lucianlazar1983** [comment]
Thank you for your fast reply, will try that because i only need my collegagues to access and manage the whole server via LDAP (We use FreeIPA) but not get in the way of how domains are managed. Will try your tip and get back if it works.
Thanks

**Comment by Programmierus** [comment]
I have implemented LDAP_FILTER in last commit (507dd95), new README.md has some hints how you can restrict LDAP sync to a certain group only.
